### ISSUE TITLE
Project licensing and public availability

### ISSUE THREAD

**Issue by jhortizo** [jhortizo/julia-mfem-poisson#1]
Let's use this space to discuss the type of license we should use for this project, and whether we are allowing the community to access it from the beginning, when we finish it, or if it will remain private.

This discussion also concerns how we should handle the availability of data inputs and outputs and the repo name.

*My proposed solution*

To make it public once the implementation arrives in a functioning state. We should correctly reference the original paper, add licensing, and collaboration instructions, and make the input data available within the repo. Keep the name as the one I proposed, something that states that it's done in Julia and it's an MFEM implementation, for SEO purposes.

**Comment by nicoguaro** [comment]
Just in case, I suggest that we use 2 licenses: one for the content (documentation, tutorials, images) and one for the software. I suggest the following:

- [Creative Commons attribution](https://creativecommons.org/licenses/by/4.0/) for content; and
- A liberal license for the software. This can be [MIT](https://opensource.org/license/MIT/) or [Modified BSD](https://opensource.org/license/bsd-3-clause/).

**Comment by nicoguaro** [comment]
Regarding the privacy of the code. I don't think that there is any advantage to keeping it private. On the other hand, from an open-science perspective, it is suggested to make the data/code available as soon as possible.

**Comment by jhortizo** [comment]
Thanks for the advice! 😁 

I already made the repo public and added the MIT license for the software. However, I don't know where to add the Creative Commons license. Would it be in the same LICENSE file? Or in a different one and a clarification note is written in the README? Either way, that one is not a priority right now, as there is no content in the repo yet.

I am keeping this issue still open, to remind me to add the right citation to the reference paper and clarify that it is a work in progress just in case.
